pool:
  name: Hosted Ubuntu 1604
steps:
- powershell: 'get-childitem -path env:'
  displayName: 'Dump web Environment Variables'

- task: DockerCompose@0
  displayName: 'Run Docker Compose up --build -d'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'Tomi Docker Hub'
    dockerComposeCommand: 'up --build -d'

- task: DockerCompose@0
  displayName: 'Run Docker Compose down'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'Tomi Docker Hub'
    dockerComposeCommand: down

- bash: 'docker images -a'
  failOnStderr: true
  displayName: 'Run Bash Script docker images -a'

- task: Docker@2
  displayName: 'Push Docker image to Docker Hub'
  inputs:
    containerRegistry: 'Tomi Docker Hub'
    repository: 'tpeltone/praqma-jenkins-casc'
    command: push
    tags: 'jcasc-$(Build.BuildId)'