pool:
  name: Hosted Ubuntu 1604
steps:
- powershell: 'get-childitem -path env:'
  displayName: 'Dump web Environment Variables'

- task: DockerCompose@0
  displayName: 'Run a Docker Compose up --build'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'Tomi Docker Hub'
    dockerComposeCommand: 'up --build -d'

- task: DockerCompose@0
  displayName: 'Run a Docker Compose down'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'Tomi Docker Hub'
    dockerComposeCommand: 'down'    

- task: Docker@0
  displayName: 'Push an image'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryConnection: 'Tomi Docker Hub'
    action: 'Push an image'
    additionalImageTags: TOMITEST
    includeSourceTags: true